### ISSUE TITLE
Prow checks are not enforced

### ISSUE THREAD

**Issue by adrcunha** [knative/observability#25]
This means PRs can be merged into observability without OWNERS approval or passing tests.

**Comment by adrcunha** [comment]
This is step 5 in https://github.com/knative/test-infra/blob/master/ci/prow_setup.md#setting-up-prow-for-a-new-repo-reviewers-assignment-and-auto-merge

**Comment by Harwayne** [comment]
/close

Based on https://github.com/knative/observability/pull/51#issuecomment-536668071 and its response, https://github.com/knative/observability/pull/51#issuecomment-536668076, I think Prow is working correctly. At least it passes the test suggested by the instructions in https://github.com/knative/observability/issues/25#issuecomment-491398421 and had reviewers added.

**Comment by adrcunha** [comment]
/reopen

This issue is not about the presubmits tests being run, but about them being required to pass in order for a PR to be submitted. This is the step 5 mentioned in the comment above. Right now, a PR can be merged even if all the presubmit tests fail.

For example, open any unmerged PR in this repo and check the status of the presubmit tests: they're not required, and even if failing GitHub allows the merge.

![image](https://user-images.githubusercontent.com/35786489/65904111-9b223d00-e372-11e9-8733-c52304b1bb98.png)

Now check how things are in a correctly set repo, like serving, for the same situation:

![image](https://user-images.githubusercontent.com/35786489/65904178-c3aa3700-e372-11e9-8aa0-edd44adeaab5.png)

**Comment by Harwayne** [comment]
/assign @mdemirhan 

Set tide as a required status check for the master branch. As specified in https://github.com/knative/test-infra/blob/master/ci/prow_setup.md#setting-up-prow-for-a-new-repo-reviewers-assignment-and-auto-merge.
