### ISSUE TITLE
update-codegen.sh is broken

### ISSUE THREAD

**Issue by poy** [knative/observability#35]
`update-codegen.sh` references k8s.io/code-generator in the vendor directory https://github.com/knative/observability/blob/94718bbb2999e84330d7de3b3e761d03c514e59f/hack/update-codegen.sh#L26, however the vendor directory does not have k8s.io/code-generator.

**Comment by wfernandes** [comment]
This is on-going issue that we are trying to resolve. We had added it as a submodule in the vendor directory but for some other reasons it was removed. We are looking into a solution that will work with go modules instead of git submodules.
