### ISSUE TITLE
support jaegar endpoint for tracing

### ISSUE THREAD

**Issue by modassarrana** [knative/observability#47]
Jaegar endpoint is required as part of kiali . At present , zipkin is supported as part of tracing.
Add jaegar endpoint as part of knative.

Below output shows that zipkin is being configured as part of knative  under istio-system namespace
Output : 
kubectl get po -n istio-system  
NAME                                      READY   STATUS      RESTARTS   AGE
istio-citadel-6cb576cb8-bwfwb             1/1     Running     0          4m22s
istio-cleanup-secrets-1.1.3-9fqjp         0/1     Completed   0          4m23s
istio-galley-8685b6778d-8hrvr             1/1     Running     0          4m23s
istio-ingressgateway-87f9cb5c-8z2rq       1/1     Running     0          4m22s
istio-pilot-577c6b579d-6rbdj              2/2     Running     0          4m22s
istio-pilot-577c6b579d-n5w4h              2/2     Running     0          4m7s
istio-policy-6887f4649-22bcc              2/2     Running     1          4m22s
istio-security-post-install-1.1.3-qfbqm   0/1     Completed   0          4m23s
istio-sidecar-injector-77f787c45-jkmn7    1/1     Running     0          4m22s
istio-telemetry-7dfd9dfdbc-hqs96          2/2     Running     1          4m22s
kiali-6c5897d9d5-4tpfs                    1/1     Running     0          4m22s
zipkin-5bf9dcc949-cj2bj                   1/1     Running     0          3m5s

Config map of kiali

kubectl get cm kiali -n istio-system -o yaml
apiVersion: v1
data:
  config.yaml: "istio_namespace: istio-system\nserver:\n  port: 20001\nexternal_services:\n
    \ istio:\n    url_service_version: http://istio-pilot:8080/version\n  jaeger:\n
    \   url: \n  grafana:\n    url: \n"
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"config.yaml":"istio_namespace: istio-system\nserver:\n  port: 20001\nexternal_services:\n  istio:\n    url_service_version: http://istio-pilot:8080/version\n  jaeger:\n    url: \n  grafana:\n    url: \n"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app":"kiali","chart":"kiali","heritage":"Tiller","release":"release-name"},"name":"kiali","namespace":"istio-system"}}
  creationTimestamp: "2019-07-16T15:30:35Z"
  labels:
    app: kiali

**Comment by Harwayne** [comment]
/close

I believe this now works. I have followed https://knative.dev/docs/serving/installing-logging-metrics-traces/#jaeger and seen traces show up correctly in Jaeger. Note that it still uses a Service named `zipkin`, but points at the Jaeger instance.

If those instructions don't work for you, please re-open the issue.
