### ISSUE TITLE
Move dependencies to use `dep`

### ISSUE THREAD

**Issue by wfernandes** [knative/observability#5]
Move away from submodules and `go modules` and use `dep` so that we can leverage pipelines and tooling already built within knative that support `dep`.

Additional Context/Reference:
- https://github.com/knative/observability/pull/2#discussion_r233562110
- https://github.com/knative/observability/pull/2#discussion_r233562378

**Comment by dprotaso** [comment]
Feel to close this  - Go 1.12 is coming out soon which defaults with module support turned on

**Comment by srinivashegde86** [comment]
The test-infra still assumes we are using dep for dependency management and all the test jobs will fail until we fix that. Can we be consistent with the other knative repos and use dep in this repo as well?

**Comment by adrcunha** [comment]
Knative/client also uses modules. They vendored test-infra so the whole test infrastructure can be used.
